Driver.class: Driver.java
	javac Driver.java

test: Driver.class
	#"Testing Wordcount on sourcefiles"
	java Driver wordcount MultiSet.java Driver.java
	#"Testing multiset with Driver class"
	java Driver multiset
